// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: proto/pipeline.proto

package pipeline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventPipeline_ProcessBatch_FullMethodName       = "/pipeline.EventPipeline/ProcessBatch"
	EventPipeline_ProcessBatchStream_FullMethodName = "/pipeline.EventPipeline/ProcessBatchStream"
)

// EventPipelineClient is the client API for EventPipeline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream.
type EventPipelineClient interface {
	ProcessBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
	ProcessBatchStream(ctx context.Context, opts ...grpc.CallOption) (EventPipeline_ProcessBatchStreamClient, error)
}

type eventPipelineClient struct {
	cc grpc.ClientConnInterface
}

func NewEventPipelineClient(cc grpc.ClientConnInterface) EventPipelineClient {
	return &eventPipelineClient{cc}
}

func (c *eventPipelineClient) ProcessBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, EventPipeline_ProcessBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventPipelineClient) ProcessBatchStream(ctx context.Context, opts ...grpc.CallOption) (EventPipeline_ProcessBatchStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventPipeline_ServiceDesc.Streams[0], EventPipeline_ProcessBatchStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &eventPipelineProcessBatchStreamClient{stream}
	return x, nil
}

type EventPipeline_ProcessBatchStreamClient interface {
	Send(*BatchRequest) error
	Recv() (*BatchResponse, error)
	grpc.ClientStream
}

type eventPipelineProcessBatchStreamClient struct {
	grpc.ClientStream
}

func (x *eventPipelineProcessBatchStreamClient) Send(m *BatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventPipelineProcessBatchStreamClient) Recv() (*BatchResponse, error) {
	m := new(BatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventPipelineServer is the server API for EventPipeline service.
// All implementations must embed UnimplementedEventPipelineServer
// for forward compatibility
type EventPipelineServer interface {
	ProcessBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	ProcessBatchStream(EventPipeline_ProcessBatchStreamServer) error
	mustEmbedUnimplementedEventPipelineServer()
}

// UnimplementedEventPipelineServer must be embedded to have forward compatible implementations.
type UnimplementedEventPipelineServer struct {
}

func (UnimplementedEventPipelineServer) ProcessBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedEventPipelineServer) ProcessBatchStream(EventPipeline_ProcessBatchStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessBatchStream not implemented")
}
func (UnimplementedEventPipelineServer) mustEmbedUnimplementedEventPipelineServer() {}

// UnsafeEventPipelineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventPipelineServer will
// result in compilation errors.
type UnsafeEventPipelineServer interface {
	mustEmbedUnimplementedEventPipelineServer()
}

func RegisterEventPipelineServer(s grpc.ServiceRegistrar, srv EventPipelineServer) {
	s.RegisterService(&EventPipeline_ServiceDesc, srv)
}

func _EventPipeline_ProcessBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventPipelineServer).ProcessBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventPipeline_ProcessBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventPipelineServer).ProcessBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventPipeline_ProcessBatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventPipelineServer).ProcessBatchStream(&eventPipelineProcessBatchStreamServer{stream})
}

type EventPipeline_ProcessBatchStreamServer interface {
	Send(*BatchResponse) error
	Recv() (*BatchRequest, error)
	grpc.ServerStream
}

type eventPipelineProcessBatchStreamServer struct {
	grpc.ServerStream
}

func (x *eventPipelineProcessBatchStreamServer) Send(m *BatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventPipelineProcessBatchStreamServer) Recv() (*BatchRequest, error) {
	m := new(BatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventPipeline_ServiceDesc is the grpc.ServiceDesc for EventPipeline service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even by copy)
var EventPipeline_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pipeline.EventPipeline",
	HandlerType: (*EventPipelineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessBatch",
			Handler:    _EventPipeline_ProcessBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessBatchStream",
			Handler:       _EventPipeline_ProcessBatchStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/pipeline.proto",
}
